# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='refresh token'),
        ),
    ]
