# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-05 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_continuous_authority_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.Payment'),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_initial_continuous_authority_payments',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_previous_initial_continuous_authority_payments_+', to='billing.Payment'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
