# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170120_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='client customer id'),
        ),
    ]
