# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_client_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adwords_dry_run',
            field=models.BooleanField(default=True, verbose_name='Do not apply Adwords changes'),
        ),
    ]
