# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_adwords_dry_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_adwords_dry_run',
            field=models.BooleanField(default=False, verbose_name='Do not apply Adwords changes'),
        ),
    ]
