# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170728_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company'),
        ),
    ]
