# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email confirmed at'),
        ),
    ]
