# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment'),
        ('accounts', '0010_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_continuous_authority_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Payment'),
        ),
    ]
