# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_initial_continuous_authority_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='initial_continuous_authority_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.Payment'),
        ),
    ]
