# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_payment_last_taken_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_last_taken_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 9, 25, 11, 38, 39, 799515)),
            preserve_default=False,
        ),
    ]
