# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def populate_uuids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')

    for user in User.objects.all():
        user.google_analytics_client_id = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170925_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_analytics_client_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='The ID used to refer to this user within Google Analytics', unique=False),
        ),
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='google_analytics_client_id',
            field=models.UUIDField(unique=True)
        )
    ]
