# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20171016_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_card_expiry_warning',
            field=models.BooleanField(default=False),
        ),
    ]
