# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20171019_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_analytics_client_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='The ID used to refer to this user within Google Analytics'),
        ),
    ]
