# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20170922_1612'),
        ('accounts', '0017_auto_20171019_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_initial_continuous_authority_payments',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_previous_initial_continuous_authority_payments_+', to='billing.Payment'),
        ),
    ]
