# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20171020_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freerolled',
            field=models.BooleanField(default=False, verbose_name='If set, this user will have their account managed for free, and will not encounter the payent step of the singup process.'),
        ),
    ]
