# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_is_freerolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_freerolled',
            field=models.BooleanField(default=False, help_text='If set, this user will have their account managed for free, and will not encounter the payent step of the signup process.', verbose_name='Freeroll this user'),
        ),
    ]
