# Generated by Django 2.2.9 on 2020-05-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20171002_1510'),
        ('accounts', '0002_auto_20191005_1551'),
    ]

    operations = [
    ]
