# Generated by Django 2.2.9 on 2020-05-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20200513_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='initial_continuous_authority_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.Payment'),
        ),
    ]
