# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom6', '0003_auto_20170918_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
