# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom6', '0004_response_response_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_code',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
