# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive. Leave empty for no upper limit.', max_digits=7, null=True, verbose_name='Maximum')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Fee in percentage', max_digits=5, verbose_name='Fee')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Pricing groups',
            },
        ),
        migrations.AddField(
            model_name='priceband',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_bands', to='billing.Pricing', verbose_name='Pricing'),
        ),
        migrations.AlterUniqueTogether(
            name='priceband',
            unique_together=set([('maximum', 'pricing')]),
        ),
    ]
