# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='priceband',
            unique_together=set([]),
        ),
    ]
