# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-12 13:15
from __future__ import unicode_literals

from decimal import Decimal

from django.db import migrations


def add_pricing_groups(apps, schema_editor):
    Pricing = apps.get_model('billing.Pricing')
    PriceBand = apps.get_model('billing.PriceBand')

    if not Pricing.objects.count():
        pricing = Pricing.objects.create()

        PriceBand.objects.create(
            pricing=pricing,
            maximum=Decimal(1000),
            fee=Decimal(10),
        )
        PriceBand.objects.create(
            pricing=pricing,
            maximum=Decimal(5000),
            fee=Decimal('7.5'),
        )
        PriceBand.objects.create(
            pricing=pricing,
            maximum=Decimal(10000),
            fee=Decimal(5),
        )
        PriceBand.objects.create(
            pricing=pricing,
            maximum=None,
            fee=Decimal(2),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20170809_1501'),
    ]

    operations = [
        migrations.RunPython(add_pricing_groups, migrations.RunPython.noop),
    ]
