# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20170912_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('SALE', 'sale'), ('VERIFY', 'verify'), ('PREAUTH', 'preauth')], max_length=7)),
                ('amount', models.PositiveIntegerField(help_text='The amount to charge the customer, in pence')),
                ('currency_code', models.CharField(help_text='The ISO-4217 formatted currency code denoting what currency to charge the customer in.', max_length=3)),
                ('transaction_unique', models.UUIDField(default=uuid.uuid4)),
                ('order_ref', models.CharField(blank=True, help_text="Free format test field to store order details, reference numbers, etc. for the Merchant's records.", max_length=255, null=True)),
                ('xref', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=63)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('customer_postcode', models.CharField(blank=True, max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number, including country code for international numbers.', regex='^\\+?(?:\\d ?){10,15}$')])),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom6.Response')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
