# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


def convert_to_micro_amounts(apps, schema_editor):
    PriceBand = apps.get_model('billing', 'PriceBand')

    for price_band in PriceBand.objects.all():
        if price_band.maximum is not None:
            price_band.maximum *= 10**6
            price_band.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceband',
            name='maximum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive. Leave empty for no upper limit.', max_digits=20, null=True, verbose_name='Maximum'),
        ),
        migrations.RunPython(convert_to_micro_amounts),
    ]
