# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20170922_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceband',
            name='maximum',
            field=models.BigIntegerField(blank=True, help_text='Inclusive. Leave empty for no upper limit.', null=True, verbose_name='Maximum'),
        ),
    ]
