# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_modifiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifierprocesslog',
            name='adwords_campaign_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifierprocesslog',
            name='parameters',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
