# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_modifiers', '0002_auto_20170125_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordactionlog',
            name='new_max_cpc',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='keywordactionlog',
            name='previous_max_cpc',
            field=models.PositiveIntegerField(),
        ),
    ]
