# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 11:56
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_modifiers', '0004_auto_20170131_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifierprocesslog',
            name='parameters',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
