# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_modifiers', '0005_auto_20170201_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifierprocesslog',
            name='is_dry_run',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
