# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_modifiers', '0007_auto_20170613_1409'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE `campaign_modifiers_keywordevent` ADD INDEX `modifier_process_log_id` (`modifier_process_log_id`)"),
        migrations.RunSQL("ALTER TABLE `campaign_modifiers_keywordevent` ADD INDEX `created_at` (`created_at`)"),
        migrations.RunSQL("ALTER TABLE `campaign_modifiers_modifierprocesslog` ADD INDEX `adwords_campaign_id` (`adwords_campaign_id`)"),
        migrations.RunSQL("ALTER TABLE `reports_campaign` ADD INDEX `adwords_campaign_id` (`adwords_campaign_id`)"),
    ]
