# Generated by Django 2.2.9 on 2021-03-31 15:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True, verbose_name='Status')),
                ('report_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Report Type')),
            ],
            options={
                'verbose_name': 'Automated Task',
                'verbose_name_plural': 'Automated Tasks',
                'db_table': 'report_scripts',
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category Name',
                'verbose_name_plural': 'Categories',
                'db_table': 'report_scripts_category',
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Id')),
                ('adwords_campaign_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adwords Campaign Id')),
                ('result', jsonfield.fields.JSONField(blank=True, help_text='Results', null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('total_records', models.PositiveIntegerField(verbose_name='Total Records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_result', to='reports.Campaign', verbose_name='Campaign Id')),
            ],
            options={
                'db_table': 'report_scripts_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Campaign', verbose_name='Campaign Id')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_scripts.ReportScripts', verbose_name='Script Id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'report_scripts_status',
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Customer Id')),
                ('adwords_campaign_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adwords Campaign Id')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Complete'), (3, 'Failed'), (4, 'No Results')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_schedule', to='reports.Campaign', verbose_name='Campaign Id')),
                ('ref_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_schedule', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_schedule', to='report_scripts.ReportScripts', verbose_name='Script Id')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_schedule', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'report_scripts_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsSafeWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Id')),
                ('safe_words', models.TextField(blank=True, help_text='(One keyword per line)', null=True, verbose_name='Safe-words')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'report_scripts_safe_words',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResultSqagQs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('new_ad_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='New Ad Group Id')),
                ('source_ad_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Ad Group Id')),
                ('source_ad_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Ad Id')),
                ('new_ad_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='New Ad Group')),
                ('apply', models.BooleanField(default=False)),
                ('ad_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Type')),
                ('final_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Final URL')),
                ('final_mobile_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Final Mobile URL')),
                ('headlines', models.TextField(blank=True, null=True, verbose_name='Headlines')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Descriptions')),
                ('headline1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Headline 1')),
                ('headline2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Headline 2')),
                ('headline3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Headline 3')),
                ('description1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description 1')),
                ('description2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description 2')),
                ('path1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Path 1')),
                ('path2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Path 2')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyword')),
                ('new_ad_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='New Ad Id')),
                ('apply_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_sqag_qs', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
            ],
            options={
                'db_table': 'report_scripts_result_sqag_qs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResultShoppingSqMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ad_group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Group Name')),
                ('search_query', models.CharField(blank=True, max_length=255, null=True, verbose_name='Search Query')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_shopping_sq_match', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
            ],
            options={
                'db_table': 'report_scripts_result_shopping_sq_match',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResultShoppingBids',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ad_group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Group Name')),
                ('ad_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Group ID')),
                ('product_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Group ID')),
                ('product_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Group')),
                ('previous_max_cpc', models.PositiveIntegerField()),
                ('new_max_cpc', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_shopping_bids', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
            ],
            options={
                'db_table': 'report_scripts_result_shopping_bids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResultOvercpa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyword')),
                ('target_cpa', models.PositiveIntegerField(default=0, verbose_name='Target CPA')),
                ('cpa', models.PositiveIntegerField(default=0, verbose_name='CPA')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Cost')),
                ('conversions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_overcpa', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
            ],
            options={
                'db_table': 'report_scripts_result_overcpa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResultNegativeKeywords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyword')),
                ('keyword_list_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyword List Name')),
                ('keyword_list_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source Ad Id')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Cost')),
                ('conversions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cpa', models.PositiveIntegerField(default=0, verbose_name='CPA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_neg_keywords', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
            ],
            options={
                'db_table': 'report_scripts_result_negative_keywords',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResultAdSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='Schedule Day')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_ad_schedule', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
            ],
            options={
                'db_table': 'report_scripts_result_ad_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScriptsResultAdgroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ad_group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Group Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_adgroup', to='report_scripts.ReportScriptsResult', verbose_name='Result Id')),
            ],
            options={
                'db_table': 'report_scripts_result_adgroup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reportscriptsresult',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_scripts.ReportScriptsSchedule', verbose_name='Schedule Id'),
        ),
        migrations.AddField(
            model_name='reportscriptsresult',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_scripts.ReportScripts', verbose_name='Script Id'),
        ),
        migrations.AddField(
            model_name='reportscriptsresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='reportscripts',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, to='report_scripts.ReportScriptsCategory', verbose_name='Categories'),
        ),
    ]
